spring.application.name=API_joueur

# Configuration MongoDB
# En Docker, on utilise la variable d'environnement.
# En local sur IntelliJ, on utilise localhost port 27018.
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27018/gatcha-player-db}