spring.application.name=API_joueur

spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}
spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27018}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:gatcha-player-db}

spring.data.mongodb.auto-index-creation=true

# --- Actuator (Health Checks) ---
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# --- External APIs ---
# URL API Auth (host.docker.internal pour Docker Desktop)
gatcha.auth-api.url=${AUTH_API_URL:http://host.docker.internal:8080/user/verify-token}