spring.application.name=API_joueur

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27018/gatcha-player-db}

spring.data.mongodb.auto-index-creation=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# On remplace 'localhost' par 'host.docker.internal' pour sortir du conteneur
gatcha.auth-api.url=http://host.docker.internal:8080/user/verify-token