spring.application.name: api_joueur

spring:
  data:
    mongodb:
      database: gatcha-player-db
      port: 27017

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
